### ISSUE TITLE
Renaming to `cordlr-loader`

### ISSUE THREAD

**Issue by jamen** [Devcord/cordlr-core-loader#1]
In the new documentation, we will have a more consistent naming scheme:
 - `cordlr-*`: Plugins
 - `cordlr-loader-*`: Loaders

Alongside the keywords `cordlr-plugin` and `cordlr-loader`.

**Comment by jamen** [comment]
@seanc are you already creating a `cordlr-loader`? If so, we can transfer that here (maybe alongside adding you to organization)

**Comment by seanc** [comment]
I decided to go with cordlr-default-loader as cordlr-loader is a plugin.

**Comment by jamen** [comment]
I've created [`cordlr-loader`](https://github.com/Devcord/cordlr-loader).  This repo can be deleted and we can all colalb on that one.
